services:
  pai-admin:
    build:
      dockerfile: Dockerfile
    container_name: pai-admin
    stop_signal: SIGINT
    environment:
      - SECRET_KEY=A_VERY_SECRET_KEY_MAKE_TO_REPLACE_THIS_KEY_123@!
      - DATA_DIR=/data
      - DATABASE_URL=sqlite:////database/app.db
      - LOG_TO_STDOUT=true
      - DELETE_FILES_ENABLED=true
      - SCRIPT_NAME=/admin
      - CONTAINER_NAME=pai-admin
      - INDEX_RUNNING_FILE='/Users/jkraemer/Downloads/Kwaai-WG-Data/index.running'
      - INDEX_COMPLETE_FILE='/Users/jkraemer/Downloads/Kwaai-WG-Data/index.complete'
      - MINIMUM_CONTAINER_UPTIME_SECONDS=60
      - MINIMUM_INDEX_UPTIME_SECONDS=300
    ports:
      - 3000:3000
    volumes:
      - database:/database
      - /Users/jkraemer/Downloads/Kwaai-WG-Data:/data
      - /Users/jkraemer/Downloads/Kwaai-WG-Data:/index
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  database:
