services:
  pai-admin:
    build:
      dockerfile: Dockerfile
    container_name: pai-admin
    environment:
      - SECRET_KEY=A_VERY_SECRET_KEY_MAKE_TO_REPLACE_THIS_KEY_123@!
      - DATA_DIR=/data
      - DATABASE_URL=sqlite:////database/app.db
      - LOG_TO_STDOUT=true
      - DELETE_FILES_ENABLED=true
      - FLASK_URL_PREFIX=/admin
    ports:
      - 3000:3000
    volumes:
      - database:/database
      - /Users/jkraemer/Downloads/Kwaai-WG-Data:/data

volumes:
  database:
