"""empty message

Revision ID: 9880a303f1e2
Revises: 36dd82e3d18d
Create Date: 2024-08-09 10:10:22.605384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9880a303f1e2'
down_revision = '36dd82e3d18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_extension'), ['extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_full_name'), ['full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_file_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_name'))
        batch_op.drop_index(batch_op.f('ix_file_full_name'))
        batch_op.drop_index(batch_op.f('ix_file_extension'))

    op.drop_table('file')
    # ### end Alembic commands ###
